---
title: "ABCD Data"
---

# ABCD Data {#abcddata}

The [Adolescent Brain Cognitive Development (ABCD) Study](https://abcdstudy.org) is the largest long-term study of brain development and child health in the United States.
This study explores how childhood experiences (such as sports, videogames, social media, unhealthy sleep patterns, and smoking) interact with each other and with a child's changing biology to affect brain development and social, behavioral, academic, health, and other outcomes.
The ABCD study follows a cohort of over 10,000 children from pre-adolescence into adulthood.

# Data Security Protocols {#dataSecurityProtocols}

All members using data from the ABCD study must abide by the following security protocols to ensure data security and participant confidentiality.

  1. Only individuals approved by Dr. Petersen and who are added to the Data Use Certificate are allowed access to this data.
  1. Members accessing this data <u><b>MUST</u></b> use the University of Iowa Research Remote Desktop Service (RRDS) when viewing or working with any data from the ABCD Study.
  Further, this <u>must be done on a University of Iowa computer</u>, unless given direct permission by Dr. Petersen.
  1. Data <b><u>CANNOT</b></u> be moved from the LSS drive where it is currently located. 
     - i.e., do not move or save any data to a personal device, a university device, or to a RRDS profile.
     - This includes any data manipulation or analysis! (e.g., .csv files, Excel files, R scripts, etc.).
  1. If a member is connected to the RRDS, they <b><u>MUST</b></u> lock the device whenever they are not seated at the computer.
      - Even if you're getting up for just a minute, the computer must be locked if it has access to ABCD data.
      This ensures that only those with permission from the University and ABCD study are able to access data.
        - To do this, press "Ctrl + Alt + Delete" and select "Lock" from the given menu.
  1. At the end of each work session, make sure that all work has been saved to the appropriate LSS drive and log out of the RRDS environment completely.
  1. If these protocols are violated for any reason, whether accidentally or intentionally, <u><b> reach out to Dr. Petersen immediately</b></u>.
     - Violation of these security protocols may result in the individual losing data privileges.

# Accessing ABCD Data {#accessingABCDdata}

## Step 1: Data Use Certificate {#dataUseCertificate}

Work with Dr. Petersen to get added to the Data Use Certificate.

## Step 2: Read (and Follow) the Lab's Protocols for Handling ABCD Data {#labProtocols}

1. Read and follow the lab's [Data Security Protocols](#dataSecurityProtocols) outlined above for handling ABCD data.
1. Read and follow the lab's Standard Operating Procedures (SOP) for handling ABCD data.
The SOP is located at the following location of the lab's LSS share: `\Lab\Studies\ABCD Data\Security Requirements for Accessing Data\`.

## Step 3: Connect to the Research Remote Desktop Service (RRDS) {#connectRRDS}

To access ABCD data, you need to access the Research Remote Desktop Service (RRDS).

1. Create an RRDS Account: <https://its.uiowa.edu/services/research-remote-desktop-service>
    - Instructions for Windows: <https://its.uiowa.edu/services/research-remote-desktop-service/connecting-rrds-using-windows-pc>
    - Instructions for Mac: <https://its.uiowa.edu/services/research-remote-desktop-service/connecting-rrds-using-mac>
1. Log in to the RRDS using your HawkID and password

If you run into issues connecting to the RRDS, please reach out to PBS IT Support (PBS-help@uiowa.edu) or Research Computing Support (research-computing@uiowa.edu) 

## Step 4: Connect to the ABCD LSS Server {#connectLSS}

Please contact Dr. Petersen to receive the network path for the ABCD Large Scale Storage (LSS) server.

<u>Mapping the Server on Windows:</u> Windows Explorer -> This PC -> Computer Tab -> Map Network Drive button: `\\server path`

<u>Mapping the Server on MacOS:</u> Finder -> Go menu -> Connect to Server: `smb://iowa\hawkid:*@server path` 

## Access Management {#accessManagement}

[XXX]

Dr. Petersen can grant or revoke access to the share, or give other people roles if they are to manage the share using the Access Management tool: <https://iam.uiowa.edu/access>

- Instructions for granting or revoking access: <https://its.uiowa.edu/support/article/118771>
- Delegate management of share access: <https://its.uiowa.edu/support/article/119191>

A few notes:

- When granting someone Read/Write or Read Only permissions and search for their name or ID, you may see both a HealthcareID and HawkID listed, <mark>select their HawkID</mark>.
- Changes take about an hour to propagate through Argon and will not be reflected in existing sessions.
- Changes are immediately reflected for SMB connections, however, users may have to remap/remount the volume or log out then back in for Windows/MacOS to be happy.

# LSS Structure {#lssStructure}

The LSS should not be accessed on your local computer. 
The LSS should **only** be accessed through the RRDS.
The main folder within the LSS is: `ABCD Study`

## Analyses Projects {#analysesProjects}

`Analyses Projects > PetersenLab` contains user folders for anyone working on projects with the ABCD data.

  1. Create a folder with your HawkID as the folder name
  1. Create a subfolder for your specific project
  1. Follow [Petersen Lab template](https://research-git.uiowa.edu/PetersenLab/Template) for structuring your project folder
  1. Follow the version control instructions [below](#versionControl)

## Data {#data}

The folder `Data > Version 6.0` contains tabulated ABCD data.

Imaging data, wearables data, and concatenated data are available for download [here](https://nbdc-datashare.lassoinformatics.com)

- [XXX] need instructions for accessing this
- NOTE: The file sizes for these data exceed the capacity of our LSS

`01-Raw` contains the raw ABCD data files that should not be altered.

`02-Processed` contains scored measures and other cleaned data for universal use.

## File types {#fileTypes}

- JSON files: data dictionary/codebook files
- Parquet files: columnar structured data (efficient for storage, can be used with the `arrow` package in R)
- TSV files: tab-separated value data files

## Available Measures {#availableMeasures}

[XXX] Add measures currently downloaded

# Version Control {#versionControl}

1. Install GitHub Desktop onto the Research Remote Desktop Service (RRDS) computer: <https://desktop.github.com>
1. Create a GitHub repository for each data analysis project using the ABCD data
1. Do NOT put data files into the GitHub repository!
    - To be safe, add the following file extensions to the `.gitignore` file in the repository (so even if data files are accidentally added to your GitHub repository folder, they will not be committed):
      ```
      *.csv
      *.tsv
      *.parquet
      *.json
      *.rds
      *.RData
      ```
