---
title: "EEG Processing Pipeline Comparison"
---

NOTE: This page is under construction and is not complete.

# Pipeline Comparison Overview

# Initial Set-Up

1. Install `MATLAB` (admin login needed)
1. Sign in to the [UIowa `MATLAB` portal](https://www.mathworks.com/academia/tah-portal/the-university-of-iowa-837756.html) using your HawkID (hawkid@uiowa.edu) and password
1. Click the "Install `MATLAB`" button in the upper right corner of the screen
1. In the new tab that opens, click the "Download for (OS)" button in the middle of the screen (`MATLAB` will automatically detect the installer version needed for your computer)
1. Open the installer file, wait for the installation files to be extracted, then sign in with an admin login when prompted
1. Once the installer is open, sign in using your HawkID (hawkid@uiowa.edu) and password
1. Agree to the terms of the license agreement
1. Use the default license option and destination folder
1. On the Products page, ensure the following products are selected:
- MATLAB
- Optimization Toolbox
- Parallel Computing Toolbox
- Signal Processing Toolbox
- Statistics and Machine Learning Toolbox
- Wavelet Toolbox
1. Choose whether to add a desktop shortcut and/or sending user experience data to MathWorks
1. Click "Begin Install"
1. Once the installation is finished, open `MATLAB` and log in using your HawkID (hawkid@uiowa.edu) and password
1. From the "Home" toolbar along the top, open Settings
1. In the menu along the left side of the Settings window, select "General" then "Java Runtime Environment"
1. Set the Java Heap Size to 3456 (double the default value of 1728), then click "OK"
- NOTE: The range of the heap size depends on your computer's processing capacity.
There is not a specific minimum or maximum, but setting the heap size to a value that is too large or too small can slow your computer down.
If your computer's default is different from the one specified above, start by doubling the heap size and make adjustments from there depending on your computer's performance.
1. Install `R` and `RStudio` using the instructions [here](R.qmd#sec-setup)
1. Clone the EEG Pipeline Comparison [GitLab repository](https://research-git.uiowa.edu/PetersenLab/SRS/srs-eeg-pipelinecomparison) to your computer
1. If you plan to use Argon/HPC for processing, also copy the EEG Pipeline Comparison repository into your Argon home directory

# Running the Pipeline Comparison

1. Open `MATLAB`
1. Using either the "Files" window on the left or the "FILE" input under the toolbar, navigate to the EEG Pipeline Comparison repository and open the `processing.m` file
1. In the toolbar along the top, go to the "Editor" pane, then click "Run"
1. Response to the prompts that appear in the Command Window using the documentation below

## Parameters

### Processing Info

NOTE: These inputs cannot be modified after entry.
If you select the wrong option, press "Ctrl+C" to stop the script.

1. **Processing data using Argon/HPC?**
Indicate whether you would (**y**) or would not (**n**) like to process the data using Argon.
If you would like to use Argon, you must have an Argon account and have your Argon home directory mapped to your computer (see the [HPC documentation](hpc.qmd) for more information).
1. **Use parallel pool for initial processing?**
Indicate whether you would like to run the initial processing steps in parallel (i.e., multiple data files simultaneously; **y**) or in series (i.e., one file at a time; **n**).
Parallel processing can be faster, but if you are processing the data on your computer rather than on Argon, it can cause your computer to run slowly, since most of its processing power will be dedicated to the EEG processing.
Additionally, because file sizes are much larger for the initial processing steps, longer data files (like the ones produced for the Stop-Signal task) can cause `MATLAB` to freeze or can fail to load if using parallel processing on your computer.
1. **Use parallel pool for pipeline processing?**
Indicate whether you would like to run the pipeline-specific processing steps in parallel (**y**) or in series (**n**).
The file sizes for this step are much smaller, even for longer tasks, so it is more feasible to run pipeline-specific processing in parallel on your computer.
However, much of your computer's processing power would still be dedicated to the EEG processing, so your computer will likely slow down (albeit to a lesser degree).
1. **Enter the path to the folder containing the raw dataset**
Enter the complete file path for the raw data that you would like to process.
If `MATLAB` cannot locate the folder, it will prompt you to re-enter the file path.
1. **Where is the raw data saved?**
Indicate whether the raw data folder is saved locally (i.e., on your computer), in the PetersenLabEEGVideo drive, or in your Argon home directory.
If you chose to process the data using Argon, you cannot process data that is saved locally, and that option will not be visible.
1. **Select processing mode**
Indicate whether you would like to process all of the files in the raw data folder (**all**) or only the files that have not yet been processed (**new**).
The **new** option assumes that you will be processing the unprocessed files using the same parameters used to process other files.

<details>
<summary>If processing new files</summary>

1. **Enter the path to the existing output folder**
Enter the complete file path to the main output folder with the data that is already processed.
The main output folder is the one that contains the `0_input_parameters` folder.
If `MATLAB` cannot locate the folder, or if the folder exists but does not contain a folder called `0_input_parameters`, it will prompt you to re-enter the file path.
1. **List of processed files not found**
This prompt will only appear if `MATLAB` cannot locate `processed_files_all.mat` within the main output folder.
When this happens, you can either specify a different list of processed files (**file**) or process all of the files in the raw data folder (**all**).
Depending on how many files have already been processed, it may be faster to close out of the script, manually create a list of the processed files, and restart.
1. **Enter the complete path to the list of processed files, including the file extension**
This prompt will only appear if you selected **file** in the previous step.
Enter the complete file path (including file name and extension) for a list of processed files.
The list does not have to be named `processed_files_all`, but it must have a `.mat` file extension.
If `MATLAB` cannot locate the file, or if the file does not have a `.mat` extension, it will prompt you to re-enter the file path.

</details>

1. **Where should processed data be saved?** or **Where is (original output folder)?**
Indicate whether the data should be (or are) saved locally (i.e., on your computer), in the PetersenLabEEGVideo drive, or in your Argon home directory.
If you chose to process the data using Argon, you cannot process data that is saved locally, and that option will not be visible unless you chose to only process new files (see next step).

NOTE: Saving data to PetersenLabEEGVideo is **strongly** discouraged unless you have already discussed it with the LC or Dr. P.
The storage space is extremely limited, and EEG data takes up a lot of space.
1. **Argon cannot access local directories**
This prompt will only appear if you chose to process data using Argon, are only processing new data files, and indicated that the existing processed data are saved locally.
Indicate whether you would like to process and save the new files using Argon (**argon**) or using your computer (**local**).
If you select **argon**, you will have to manually move the newly processed files to the main output directly, and combine the QC files, error logs, and processed files lists manually when processing is complete.
1. **Enter the local path to your Argon home directory**
This prompt will only appear if you are processing data using Argon, if your raw data are in Argon, or if you chose to save outputs in Argon.
Enter the "base" file path for your Argon home directory.
On Windows, this path is typically one letter followed by a colon (e.g., `X:`).
If `MATLAB` cannot locate the folder, it will prompt you to re-enter it.
If you indicated that you are using data stored in Argon, but the Argon folder you provided is not found in the file path for that data, the script will stop running with an error.
1. **Enter the local path to PetersenLabEEGVideo**
This prompt will only appear if your raw data are in LSS or if you chose to save outputs in LSS.
Enter the "base" file path for the PetersenLabEEGVideo drive.
On Windows, this path is typically one letter followed by a colon (e.g., `Y:`).
If `MATLAB` cannot locate the folder, it will prompt you to re-enter it.
If you indicated that you are using data stored in PetersenLabEEGVideo, but the LSS folder you provided is not found in the file path for that data, the script will stop running with an error.

### Parameter Set-Up

NOTE: These inputs cannot be modified after entry.
If you select the wrong option, press "Ctrl+C" to stop the script.

1. **Load pre-existing set of input parameters?**
This prompt will only appear if you chose to process all data in the raw data folder.
If you are only processing new files, `MATLAB` assumes that you will load the parameter file used with the existing processed files.
Pre-existing parameters must be saved as a `.mat` file and include all of the fields required by the processing script.
To avoid processing errors, it is strongly recommended that you use a parameter file generated by the pipeline comparison script.

#### Pre-Existing Parameters

1. **Enter the path to the parameter file**
This prompt will only appear if you chose to load a pre-existing parameter file.
If you are only processing new data files, `MATLAB` will search the original output folder for a parameter file and only display this prompt if it does not find one.
Enter the complete path to the parameter file you would like to use, including the file name and extension.
If `MATLAB` cannot locate the file, it will prompt you to re-enter it.
1. **Change an existing parameter?**
`MATLAB` will display the parameters from the loaded parameter file.
If there is an error at this step, the parameter file you specified is likely from an older version of the pipeline comparison script and is missing necessary parameters.
You will need to manually re-enter the parameters.
If you confirm the parameters, `MATLAB` will proceed to the next processing step.
If not, you will be directed to the parameter change menu.
1. **Run pipeline comparison after processing?**
This prompt will only appear if your parameter file has multiple pipelines selected.
This option will generate a few additional files to use in the `generalizability.Rmd` script (see below).

#### New Parameter File

1. **Select pipeline**
This prompt will only appear if you chose to save data in LSS or Argon.
Because these locations have much more limited storage space, the script defaults to running only one pipeline at a time.
Enter the pipeline you would like to use.
1. **Run all pipelines?**
This prompt will only appear if you chose to save data locally.
This option includes APICE, HAPPE, MADE, NEAR, and RELAX-Jr.
If you are running multiple pipelines, verify that your computer has enough space to store all of the data.
For reference, folder sizes for each task for one pipeline are shown below.
The initial output is only generated once, regardless of how many pipelines are used.
The "Total" column includes initial output, HAPPE output, error files, and output logs, but does not include intermediate outputs or pipeline comparison

| ----- | ----- | ----- | ----- | ----- |
| Task  | Files | Initial Output  | HAPPE Output  | Total |
| ----- | ----- | ----- | ----- | ----- |
| Oddball | 569 | 269 GB  | 118 GB  | 391 GB  |
| Fish-Sharks | 566 | 362 GB  | 49.2 GB | 412 GB  |
| Stop-Signal | 546 | 567 GB  | 114 GB  | 682 GB  |
| ----- | ----- | ----- | ----- | ----- |

1. **Enter the pipeline(s) you would like to run**
This prompt will only appear if you chose not to run all pipelines.
Enter at least one pipeline to use for processing.
If you are running multiple pipelines, verify that your computer has enough space to store all of the data.
See the table above for approximate folder sizes.

### Initial Processing

Before showing the next set of prompts, the script sets several parameters based on the lab's EEG equipment.
These include the raw data format, cap layout, electrode coordinate file, and channel labels.
In the (extremely unlikely) event that you need to change any of these, you must do so manually by editing the `parameters.m` file.

1. **Channels of interest?**
Indicate whether you would like to include all available channels (**all**) or only a subset of channels (**coi**).
If you are confident about the channel(s) you expect to see results in, choosing a subset of channels can help save space and decrease processing time.
However, if you are unsure about the specificity of your results or you plan to do exploratory analysis, including all channels is recommended.
1. **Enter channels to exclude**
This prompt will only appear if you chose to include a subset of channels to process.
Enter the channels that you would like to REMOVE from processing, using the "E#" label format.
1. **Data type**
Indicate whether you are processing baseline/resting-state (**rest**) or task-related (**task**) data.
This question does NOT determine whether data will be segmented.

<details>
<summary>Task-Related Data</summary>

The following prompts will only appear if you are processing task-related EEG data.

1. **Performing event-related potential (ERP) analysis?**
Indicate whether you will be using the processed data to examine ERPs.
ERP processing can be strongly affected by certain filtering and data cleaning procedures, and this setting influences which options will be available to you later.
1. **Which task are you analyzing?**
Indicate which task your data is from.
If you select one of the existing tasks, the onset tag and condition parameters will be set automatically.
If not, you will receive additional prompts for onset tag and condition information.
Additionally, accuracy coding for Fish-Sharks and Stop-Signal are built in to the processing script, but accuracy coding for other tasks must be completed before running the pipeline.

<details>
<summary>Other Tasks</summary>

1. **Enter the onset tags**
Enter the tags used to label the trials in the EEG task.
If you are not sure what tags were used, see the [Appendix](#sec-onset-tags).
When entering tags, include any plus signs, but do not include quotation marks.
1. **Do multiple onset tags belong to a single condition?**
Indicate whether any of the task onset tags belong to a larger category.
For example, in the Fish-Sharks task, we have onset tags for correct Go trials, incorrect Go trials, correct No-Go trials, and incorrect No-Go trials.
We then include Go and No-Go as conditions.
1. **Enter each condition followed by its corresponding onset tags**
This prompt will only appear if you indicated that your task has conditions.
The condition name can be whatever makes sense, but the onset tags must include all of the tags provided above, and no additional onset tags.
Additionally, each condition must contain at least two onset tags.

</details>

</details>

1. **Resample data?**
Indicate whether you would like to downsample the data.
The lab's equipment samples data at 1000Hz, which means it records 1000 measurements per channel per second during a task.
If you are processing a very long data set, or if you are not segmenting the data later, downsampling the data can be helpful for reducing file sizes.
For more complicated analysis, especially analysis involving high-frequency signals, keeping the original sampling frequency is typically recommended.
1. **Select sample frequency**
This prompt will only appear if you indicated that you would like to resample the data.
Indicate the new frequency you would like the data to have.
The **1000** option is a holdover from the `HAPPE` pipeline parameter file--because the lab's data is already at this frequency, selecting this option will not affect the data.
1. **Filtering method**
Indicate whether you would like to use high-pass, low-pass, band-pass, or no filter on the data.
Because we process child EEG, performing some amount of filtering is strongly recommended.
A high-pass filter will remove lower frequencies, a low-pass filter will remove higher frequencies, and a band-pass filter will remove both.
1. **Filter type**
This prompt will only appear if you selected a filtering option.
The **FIR** (**F**inite **I**mpulse **R**esponse) option is generally preferred for EEG processing since it preserves the "true" signal and is stable over time.
However, it requires more computational power to run, though the lab's tasks are short enough that this generally doesn't cause problems.
The **IIR** (**I**nfinite **I**mpulse **R**esponse) option requires less computational power, but since it relies on its own output, it can distort signal and/or become unstable over time.
1. **Enter low-pass filter**
This prompt will only appear if you selected the low-pass or band-pass filtering option.
Input the highest frequency you would like to keep in your data.
The vast majority of analysis will only involve frequencies below 50Hz, which greatly reduces signals from skin conductance, muscle movements, and electrical line noise.
Because time-frequency analysis is essentially a structured set of filters, there are few recommendations for low-pass cutoffs.
However, ERP analysis is quite sensitive to filter settings, so the low-pass filter cutoff can depend on the ERP of interest (see [Zhang et al., 2024](https://onlinelibrary.wiley.com/doi/10.1111/psyp.14530)).
1. **Enter high-pass filter**
This prompt will only appear if you selected the high-pass or band-pass filtering option.
Input the lowest frequency you would like to keep in your data.
If you plan to apply ICA to the data, this value should be at least 1Hz.
As with the low-pass filter, there are few cutoff recommendations for time-frequency analysis, but ERP can be greatly affected by the cutoff value.
Additionally, most ERP high-pass filter cutoffs fall well below the 1Hz cutoff recommended for ICA, so use caution if applying ICA for ERP analysis.

<details>
<summary>Line Noise Reduction</summary>

The following prompts will only appear if you selected a low-pass frequency cutoff greater than or equal to 60Hz, or if you did not enable low-pass filtering.
"Line noise" refers to the artifact caused by electrical frequencies in the wires (or "lines") near the EEG equipment.
These frequencies cause a very large spike in signal strength at the line noise frequency, which is 60Hz in the Unites States and 50Hz in most other places.
They can also cause signal spikes at harmonic frequencies (i.e., multiples of the line noise frequency) if the noise is very strong.

1. **Line noise reduction method?**
Indicate which line noise reduction method to apply to the data.
The notch (FIR) and Butterworth (IIR) filters operate as reverse bandpass filters--they keep frequencies below the lower cutoff and above the higher cutoff.
The strengths and limitations of FIR and IIR filters in this context are the same as the strengths and limitations described above.
Both the standard notch filter and the IIR filter are relatively quick to apply, but they both leave a gap in the signal at the line noise frequency, and they can lead to edge artifacts on either side of the line noise frequency.
The CleanLine and ZapLine options aim to remove the line noise artifact while preserving the true EEG signal at the line noise frequency, with the trade-off of requiring much more processing power (and processing time).
CleanLine operates primarily in the time domain--it assumes that the line noise signal varies over time, so the regression model it uses to identify and remove that signal also varies over time.
As a result, it applies this non-stationary model to each channel individually (i.e., it is univariate).
ZapLine, on the other hand, operates primarily in the spatio-spectral domain, meaning it assumes that the relationships among the electrodes are consistent over time and applies the same model to all channels collectively (i.e., it is multivariate).
ZapLine's stationarity assumption is often violated in "real-world" data, but CleanLine takes significantly longer to run.
Some researchers recommend using CleanLine and ZapLine in a complementary fashion (e.g., [Miyakoshi et al., 2021](https://pmc.ncbi.nlm.nih.gov/articles/PMC7873913/)), but this has not been implemented in our code (yet).
1. **Enter lower cutoff**
This prompt will only appear if you selected the notch or Butterworth option.
Input the lower cutoff for the line noise filter (typically 1-2Hz below the line noise frequency).
1. **Enter higher cutoff**
This prompt will only appear if you selected the notch or Butterworth option.
Input the higher cutoff for the line noise filter (typically 1-2Hz above the line noise frequency).
1. **Are there additional frequencies to reduce?**
This prompt will only appear if you selected the CleanLine option.
As mentioned above, very strong line noise can cause additional artifacts at harmonic frequencies.
Unless you know there are harmonic artifacts in your data, providing additional frequencies is typically unnecessary and will increase processing time.
1. **Enter the frequencies to pass through noise reduction**
This prompt will only appear if you selected the CleanLine option and indicated that there are additional frequencies to reduce.
Input the harmonic frequencies to add to the CleanLine reduction.
These frequencies will often be multiples of the line noise frequency (e.g., 120Hz), but can also be "partial" multiples (e.g., 30Hz, 90Hz) if the line noise is particularly strong.
If you are using this option, visual data inspection to identify harmonics is recommended.

### Bad Channel Detection

The prompts for this section vary considerably depending on the pipeline(s) select earlier in the script.
Pipeline-specific prompts are preceded by the pipeline name and only appear if that pipeline was selected.

1. **Perform bad channel rejection?**
Indicate whether you would like to *reject* bad channels identified during pre-processing.
If you choose not to reject bad channels, `MATLAB` will identify bad channels using the default settings and keep them in the data set.
This can be helpful in cases where you are analyzing a small subset of channels and for analyses that require all data files to have the same channels present.
If you choose not to reject bad channels, proceed to [Data Cleaning](#sec-data-cleaning).
1. **HAPPE: Run bad channel rejection before or after wavelet thresholding?**
Indicate whether bad channels should be removed before or after wavelet thresholding.
Because wavelet thresholding "flattens" the data amplitude, the bad channel identification parameters differ based on when they are applied.
Additionally, because wavelet thresholding is a data cleaning step, more channels tend to be rejected if bad channel rejection is applied beforehand.
1. **APICE: Use custom thresholds?**
Indicate whether you would like to adjust any of the default APICE parameters for bad channel/artifact detection.
If you choose to use custom parameters, you will need to modify the files directly--the script will not prompt you for them.
 Refer to [Flo et al., 2022](https://doi.org/10.1016/j.dcn.2022.101077) for documentation on the various parameters.
`MATLAB` will display the file path and the relevant parameter files, and it will wait until you confirm that you have finished editing the parameters.
1. **NEAR: Use all bad channel detection methods?**
Indicate whether you would like to use all three of NEAR's bad channel detection methods (flat signals, local outlier factor, and periodogram analysis).
"Flat signals" include channels identified as having no signal for 5s or more.
The local outlier factor (LOF) algorithm evaluates signal based on the distances between electrodes and their neighbors and is calculated by comparing how "reachable" a given channel is to how "reachable" its neighbors are.
If a channel is less reachable than its neighbors, it is considered a potential outlier and removed (for a more detailed explanation, see [Kumaravel et al., 2022](https://doi.org/10.1016/j.dcn.2022.101068)).
Periodogram analysis is based on findings that motion-related artifacts tend to manifest as increased power in the beta frequency range with concomitant decreased power in the delta and alpha ranges ([Georgieva et al., 2020](https://doi.org/10.3389/fnins.2020.00352)).
The creators of the NEAR pipeline note that the bad channels identified by periodogram are also identified by the flat signal and LOF methods, so it may not be necessary to implement.
All three of these methods run using the default settings recommended by the NEAR authors, which are specified in the `parameters.m` script.
1. **NEAR: Enter bad channel detection methods**
This prompt will only appear if you chose not to use all bad channel detection methods for NEAR.
Input the bad channel detection methods you would like to use for the data.

NOTE: RELAX-Jr's bad channel detection is built in to its data cleaning procedures.
Bad channels are identified using the default settings recommended by the RELAX-Jr authors, which are specified in the `parameters.m` script.

### Data Cleaning (#sec-data-cleaning)

# Appendix

## Check Onset Tags (#sec-onset-tags)

1. Using either the "Files" window on the left or the "FILE" input under the toolbar, navigate to the EEG Pipeline Comparison repository
1. Add the necessary folders to the `MATLAB` path:

    ```matlab
    % add pipeline_scripts to path
    addpath(genpath([pwd filesep 'pipeline_scripts']));
    
    % temporary variable to cut down on text
    eeglabDir = ['HAPPE' filesep 'packages' filesep 'eeglab2024.0'];
    
    % pipeline paths
    addpath('HAPPE', ['HAPPE' filesep 'packages'], ...
    ['HAPPE' filesep 'packages' filesep 'eeglab2024.0'], ...
    genpath([eeglabDir filesep 'functions']));
    rmpath(genpath([eeglabDir filesep 'functions' filesep 'octavefunc']));
    pluginDir = strcat(eeglabDir, filesep, 'plugins', filesep, ...
    {dir([eeglabDir filesep 'plugins']).name}, '; ');
    addpath([pluginDir{:}]);
    ```
    
1. Using either the "Files" window on the left or the "FILE" input under the toolbar, navigate to the folder containing the raw data
1. Load a raw data file:

    ```matlab
    EEG = pop_loadset('name_of_file.mff', 'code');
    ```
    
1. Once the file loads, double click on the `EEG` variable in the Workspace to open the structure
1. In the `EEG` structure, locate the `events` field, then double click on it to open
1. The `code` column will show the onset tags for the entire task
    - NOTE: There are often several onset tags for a given trial (e.g., `bgin`, `TRSP`, `resp`).
    Only include the onset tags that are relevant to the comparison(s) you are making.
    These tags often (but not always) end in '+' and are usually added by the software used to run the task.






