---
title: "Data Analysis Guides for the Developmental Psychopathology Lab"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  comment = "")
```

- [Bayesian Analysis](bayesian.html)
- [Data Management](dataManagement.html)
- [Developmental Scaling](developmentalScaling.html)
- [Directed Acyclic Graphs](dags.html)
- [Electroencaphalography/Event-Related Potentials](eegERP.html)
- [Exploratory Data Analysis](eda.html)
- [Factor Analysis](factorAnalysis.html)
- [Figures](figures.html)
- [`Git`, `GitLab`, and `GitHub`](git.html)
- [Hierarchical Linear Modeling](hlm.html)
- [High-Performance Computing](hpc.html)
- [`jamovi`](jamovi.html)
- [`JATOS` (Just Another Tool for Online Studies)](jatos.html)
- [`jsPsych`](jsPsych.html)
- [Item Response Theory](irt.html)
- [LAMP (Linux, Apache, MySQL, PHP)](lamp.html)
- [Longitudinal Data Analysis](lda.html)
- [Markdown](markdown.html)
- [Mediation](sem.html#mediation)
- [Moderation/Interaction](regression.html#moderation)
- [`Mplus`](mplus.html)
- [Multiple Imputation](multipleImputation.html)
- [Open Science Framework](osf.html)
- [Principal Component Analysis](pca.html)
- [`Python`](https://devpsylab.github.io/pythonDataAnalysisGuides)
- [`R`](R.html)
- [Regression](regression.html)
- [`SPSS`](SPSS.html)
- [Statistics](statistics.html)
- [Structural Equation Modeling](sem.html)
