---
title: "Data Analysis Guides for the Developmental Psychopathology Lab"
---

- [ABCD Data](abcdData.qmd)
- [Bayesian Analysis](bayesian.qmd)
- [Data Management](dataManagement.qmd)
- [Developmental Scaling](developmentalScaling.qmd)
- [Directed Acyclic Graphs](dags.qmd)
- [Electroencephalography/Event-Related Potentials](eegERP.qmd)
- [Exploratory Data Analysis](eda.qmd)
- [Factor Analysis](factorAnalysis.qmd)
- [Figures](figures.qmd)
- [`Git`, `GitLab`, and `GitHub`](git.qmd)
- [Hierarchical Linear Modeling (HLM)](hlm.qmd)
- [High-Performance Computing](hpc.qmd)
- [`jamovi`](jamovi.qmd)
- [`JATOS` (Just Another Tool for Online Studies)](jatos.qmd)
- [`jsPsych`](jsPsych.qmd)
- [Item Response Theory (IRT)](irt.qmd)
- [LAMP (Linux, Apache, MySQL, PHP) Server](lamp.qmd)
- [Longitudinal Data Analysis](lda.qmd)
- [Markdown](markdown.qmd)
- Mediation in [SEM](sem.qmd#sec-mediation) or [Bayesian modeling](bayesian.qmd#sec-multilevelMediation)
- Moderation/Interaction in [multiple regression](regression.qmd#sec-moderation), [HLM](hlm.qmd#sec-moderation), [Bayesian modeling](bayesian.qmd#sec-multilevelModeration), or [SEM](sem.qmd#sec-moderation)
- [`Mplus`](mplus.qmd)
- [Multiple Imputation](multipleImputation.qmd)
- [Open Science Framework](osf.qmd)
- [Principal Component Analysis](pca.qmd)
- [`Python`](https://devpsylab.github.io/pythonDataAnalysisGuides)
- [`R`](R.qmd)
- [Regression](regression.qmd)
- [`SPSS`](SPSS.qmd)
- [Statistics](statistics.qmd)
- [Tables](tables.qmd)
- [Structural Equation Modeling (SEM)](sem.qmd)
