---
title: "Longitudinal Data Analysis"
---

# Approaches for Modeling Longitudinal Data {#sec-approaches}

- [Growth curve model](hlm.qmd#sec-gcm)
- [Latent growth curve model](sem.qmd#sec-lgcm)
- [Latent change score model](sem.qmd#sec-lcsm)
- [Cross-lagged panel model](sem.qmd#sec-clpm)
- [Latent curve model with structured residuals](sem.qmd#sec-lcm-sr)

# Longitudinal Scores are on the Same Statistical Scale Across Time

- [Tests of longitudinal measurement invariance](sem.qmd#sec-longitudinalMI)

# Estimating Nonlinear Growth {#sec-nonlinear}

There are a variety of ways to estimate nonlinear growth in a growth curve model using a [mixed-effects](hlm.qmd) or [structural equation model](sem.qmd):

- polynomial growth model
  - fractional polynomial model (more parsimonious than traditional polynomials because can capture nonlinear growth with fewer parameters, thus reducing overfitting)
- piecewise/spline model
  - can have fixed or random knots
  - location of knots can be estimated for the data
  - each individual can have a different numbers of knots and different location for the knots
- latent basis growth model
  - can specify the rate of change between T1 and T2 to be one; can allow the rate of change to freely vary between remaining timepoints
- exponential growth model
- logistic growth model
- logarithmic growth model
  - e.g., "an exponential pattern of change—in which change appears to 'level off' over time—can be approximated through linear (and potentially quadratic) slopes for a natural-log-transformed" version of time in a [mixed-effects model](hlm.qmd) or by fixing the latent change factor loadings to these values in [SEM](sem.qmd) (Hoffman, 2025)
- generalized additive model
- nonparametric growth model (e.g., kernel smoothing)
- Gompertz growth model
- Richards growth model
- Taylor series approximation model
- [latent change score model](sem.qmd#sec-lcsm)
