---
title: "Structural Equation Modeling"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE,
                      comment = "",
                      class.source = "fold-show")
```

# Preamble

## Install Libraries

```{r, class.source = "fold-hide"}
#install.packages("remotes")
#remotes::install_git("https://research-git.uiowa.edu/PetersenLab/petersenlab.git")
```

## Load Libraries

```{r, message = FALSE, warning = FALSE, class.source = "fold-hide"}
library("lavaan")
library("semTools")
library("semPlot")
```

# Simulate Data

```{r, class.source = "fold-hide"}
set.seed(52242)

X <- rnorm(100)
M <- 0.5*X + rnorm(100)
Y <- 0.7*M + rnorm(100)

mydata <- data.frame(X = X, Y = Y, M = M)
```

# Import data

# Overview

https://isaactpetersen.github.io/Principles-Psychological-Assessment/sem.html

# Analysis examples

https://isaactpetersen.github.io/Principles-Psychological-Assessment/sem.html#semModel-sem

# Mediation {#mediation}

## Model Syntax

```{r}
mediationModel <- '
# direct effect (cPrime)
Y ~ direct*X

# mediator
M ~ a*X
Y ~ b*M

# indirect effect = a*b
indirect := a*b

# total effect (c)
total := direct + indirect
'
```

## Fit the Model

```{r}
mediationFit <- sem(mediationModel,
                    data = mydata,
                    se = "bootstrap",
                    bootstrap = 1000, # generally use 10,000 bootstrap draws; this example uses 1,000 for speed
                    missing = "ML",
                    estimator = "ML",
                    std.lv = TRUE)
```

## Summary Output

```{r}
summary(mediationFit,
        fit.measures = TRUE,
        standardized = TRUE,
        rsquare = TRUE)
```

## Indirect Effect

```{r}
parameterEstimates(mediationFit,
                   boot.ci.type = "bca.simple",
                   standardized = TRUE)
```

## Estimates of Model Fit

```{r}
fitMeasures(mediationFit, fit.measures = c("chisq", "df", "pvalue",
                                           "rmsea", "cfi", "tli", "srmr"))
```

## Residuals

```{r}
residuals(mediationFit, type = "cor")
```

## Modification Indices

```{r}
modificationindices(mediationFit, sort. = TRUE)
```

## Internal Consistency Reliability

```{r}
compRelSEM(mediationFit)
```

## Path Diagram

```{r}
semPaths(mediationFit,
         what = "Std.all",
         layout = "tree2",
         edge.label.cex = 1.5)
```

# Power analysis

https://isaactpetersen.github.io/Principles-Psychological-Assessment/sem.html#monteCarloPowerAnalysis

# Session Info

```{r, class.source = "fold-hide"}
sessionInfo()
```
