---
title: "Statistics"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  comment = "")
```

# Learning Statistics {#learningStatistics}

Here are resources for learning statistics:

- OpenIntro Statistics: https://www.openintro.org/book/os/
- Introductory Statistics: https://openstax.org/details/books/introductory-statistics-2e

# Workshops {#workshops}

Here are potential sources for workshops on various statistical topics:

- https://centerstat.org
- https://smart-workshops.com
- https://www.statscamp.org
- https://statisticalhorizons.com
- https://stats.oarc.ucla.edu/other/mult-pkg/seminars/
- https://datascience-workshop.uiowa.edu/resources

# Statistical Decision Tree {#statisticalDecisionTree}

![A Statistical Decision Tree For Choosing an Appropriate Statistical Procedure. Adapted from: <https://commons.wikimedia.org/wiki/File:InferentialStatisticalDecisionMakingTrees.pdf>. The original source is: Corston, R., & Colman, A. M. (2000). *A crash course in SPSS for Windows*. Wiley-Blackwell. Changes were made to the original, including the addition of several statistical tests.](images/statisticalDecisionTree.png)

![A Statistical Decision Tree For Choosing an Appropriate Statistical Procedure, Re-Formulated in a Regression Framework. Adapted from: <https://commons.wikimedia.org/wiki/File:InferentialStatisticalDecisionMakingTrees.pdf>. The original source is: Corston, R. & Colman, A. M. (2000). *A crash course in SPSS for Windows*. Wiley-Blackwell. Changes were made to the original, including re-formulating the tests in a regression framework.](images/statisticalDecisionTreeRegression.png)
