---
title: "Statistics"
---

# Learning Statistics {#sec-learningStatistics}

Here are resources for learning statistics:

- OpenIntro Statistics: <https://www.openintro.org/book/os/>
- Introductory Statistics: <https://openstax.org/details/books/introductory-statistics-2e>
- [Fantasy Football Analytics: Statistics, Prediction, and Empiricism Using `R`](https://isaactpetersen.github.io/Fantasy-Football-Analytics-Textbook): A resource I wrote to help people learn statistics and [`R`](R.qmd) in the context of fantasy football
- [Principles of Psychological Assessment: With Applied Examples in `R`](https://isaactpetersen.github.io/Fantasy-Football-Analytics-Textbook): A resource I wrote for applying principles of assessment using [`R`](R.qmd)

# Workshops {#sec-workshops}

Here are potential sources for workshops on various statistical topics:

- <https://centerstat.org>
- <https://smart-workshops.com>
- <https://www.statscamp.org>
- <https://statisticalhorizons.com>
- <https://instats.org>
- <https://stats.oarc.ucla.edu/other/mult-pkg/seminars/>
- <https://datascience-workshop.uiowa.edu/resources>

# Statistical Decision Tree {#sec-statisticalDecisionTree}

![A Statistical Decision Tree For Choosing an Appropriate Statistical Procedure. Adapted from: <https://commons.wikimedia.org/wiki/File:InferentialStatisticalDecisionMakingTrees.pdf> (archived at <https://perma.cc/L2QR-ALFA>). The original source is: Corston, R., & Colman, A. M. (2000). *A crash course in SPSS for Windows*. Wiley-Blackwell. Changes were made to the original, including the addition of several statistical tests.](images/statisticalDecisionTree.png)

![A Statistical Decision Tree For Choosing an Appropriate Statistical Procedure, Re-Formulated in a Regression Framework. Adapted from: <https://commons.wikimedia.org/wiki/File:InferentialStatisticalDecisionMakingTrees.pdf> (archived at <https://perma.cc/L2QR-ALFA>). The original source is: Corston, R. & Colman, A. M. (2000). *A crash course in SPSS for Windows*. Wiley-Blackwell. Changes were made to the original, including re-formulating the tests in a regression framework.](images/statisticalDecisionTreeRegression.png)
